# Site wide configuration

title:            amingilani
locale:           en_US
url:              //amin.gilani.me


# Jekyll configuration

permalink:   pretty
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Amin Shah Gilani
  avatar: https://avatars0.githubusercontent.com/u/1188552?v=2&s=460
  bio: "Yet another humanoid."
  email:
  disqus-shortname: amingilani
  twitter: amingilani
  facebook: aminshahgilani
  google:
    plus: aminshahgilani
    analytics: UA-36754712-2
    verify:
    ad-client: ca-pub-2244833599847323
    ad-slot: 3914920293
  bing-verify:
  github: amingilani
  stackoverflow: 3970701/amingilani
  linkedin: #username
  instagram: amingilani
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam:
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
